# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Monique Meyer
title: Junior Software Engineer
email: meyer.monique93@gmail.com
website: https://github.com/momeyer

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  momeyer
linkedin_username: monique-meyer-443384162

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
# about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Monique Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempus justo id elit vehicula, nec elementum leo sollicitudin. Donec vel pharetra urna. Etiam lacinia lobortis neque, nec pellentesque mauris semper quis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse vitae iaculis quam. Phasellus ultrices, metus in lobortis pretium, libero ex volutpat tellus, scelerisque cursus quam nisi at ante. Pellentesque vitae lobortis enim. Fusce efficitur turpis eu odio consequat, eu sagittis arcu varius. Integer purus lacus, semper in libero ac, pretium fermentum massa. Aenean sed lorem tempor, volutpat nunc nec, faucibus nisl.
content:
  - title: Codam Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: ðŸš Minishell - In Progress 
        link: https://github.com/codamMeyer/minishell
        # link_text: Project Website
        additional_links:
          # - title:  Minishell - In progress
          #   icon: fab fa-github
          #   url: https://github.com/codamMeyer/minishell
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempus justo id elit vehicula, nec elementum leo sollicitudin. Donec vel pharetra urna. Etiam lacinia lobortis neque, nec pellentesque mauris semper quis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse vitae iaculis quam. Phasellus ultrices, metus in lobortis pretium, libero ex volutpat tellus, scelerisque cursus quam nisi at ante. Pellentesque vitae lobortis enim. Fusce efficitur turpis eu odio consequat, eu sagittis arcu varius. Integer purus lacus, semper in libero ac, pretium fermentum massa. Aenean sed lorem tempor, volutpat nunc nec, faucibus nisl..
        description: | # this will include new lines to allow paragraphs
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempus justo id elit vehicula, nec elementum leo sollicitudin. Donec vel pharetra urna. Etiam lacinia lobortis neque, nec pellentesque mauris semper quis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse vitae iaculis quam. Phasellus ultrices, metus in lobortis pretium, libero ex volutpat tellus, scelerisque cursus quam nisi at ante. Pellentesque vitae lobortis enim. Fusce efficitur turpis eu odio consequat, eu sagittis arcu varius. Integer purus lacus, semper in libero ac, pretium fermentum massa. Aenean sed lorem tempor, volutpat nunc nec, faucibus nisl.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Company
        link: ---
        # link_text: boringcompany.com
        sub_title: ---
        caption: November 2017 - Present
        quote: >
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempus justo id elit vehicula, nec elementum leo sollicitudin. Donec vel pharetra urna. Etiam lacinia lobortis neque, nec pellentesque mauris semper quis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse vitae iaculis quam. Phasellus ultrices, metus in lobortis pretium, libero ex volutpat tellus, scelerisque cursus quam nisi at ante. Pellentesque vitae lobortis enim. Fusce efficitur turpis eu odio consequat, eu sagittis arcu varius. Integer purus lacus, semper in libero ac, pretium fermentum massa. Aenean sed lorem tempor, volutpat nunc nec, faucibus nisl.
        description: | # this will include new lines to allow paragraphs
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempus justo id elit vehicula, nec elementum leo sollicitudin. Donec vel pharetra urna. Etiam lacinia lobortis neque, nec pellentesque mauris semper quis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse vitae iaculis quam. Phasellus ultrices, metus in lobortis pretium, libero ex volutpat tellus, scelerisque cursus quam nisi at ante. Pellentesque vitae lobortis enim. Fusce efficitur turpis eu odio consequat, eu sagittis arcu varius. Integer purus lacus, semper in libero ac, pretium fermentum massa. Aenean sed lorem tempor, volutpat nunc nec, faucibus nisl.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ---
        caption: 2010 - 2013
        sub_title: ---
        quote: >
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempus justo id elit vehicula, nec elementum leo sollicitudin. Donec vel pharetra urna. Etiam lacinia lobortis neque, nec pellentesque mauris semper quis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse vitae iaculis quam. Phasellus ultrices, metus in lobortis pretium, libero ex volutpat tellus, scelerisque cursus quam nisi at ante. Pellentesque vitae lobortis enim. Fusce efficitur turpis eu odio consequat, eu sagittis arcu varius. Integer purus lacus, semper in libero ac, pretium fermentum massa. Aenean sed lorem tempor, volutpat nunc nec, faucibus nisl.
        description: | # this will include new lines to allow paragraphs
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempus justo id elit vehicula, nec elementum leo sollicitudin. Donec vel pharetra urna. Etiam lacinia lobortis neque, nec pellentesque mauris semper quis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse vitae iaculis quam. Phasellus ultrices, metus in lobortis pretium, libero ex volutpat tellus, scelerisque cursus quam nisi at ante. Pellentesque vitae lobortis enim. Fusce efficitur turpis eu odio consequat, eu sagittis arcu varius. Integer purus lacus, semper in libero ac, pretium fermentum massa. Aenean sed lorem tempor, volutpat nunc nec, faucibus nisl.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempus justo id elit vehicula, nec elementum leo sollicitudin. Donec vel pharetra urna. Etiam lacinia lobortis neque, nec pellentesque mauris semper quis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse vitae iaculis quam. Phasellus ultrices, metus in lobortis pretium, libero ex volutpat tellus, scelerisque cursus quam nisi at ante. Pellentesque vitae lobortis enim. Fusce efficitur turpis eu odio consequat, eu sagittis arcu varius. Integer purus lacus, semper in libero ac, pretium fermentum massa. Aenean sed lorem tempor, volutpat nunc nec, faucibus nisl.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tempus justo id elit vehicula, nec elementum leo sollicitudin. Donec vel pharetra urna. Etiam lacinia lobortis neque, nec pellentesque mauris semper quis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse vitae iaculis quam. Phasellus ultrices, metus in lobortis pretium, libero ex volutpat tellus, scelerisque cursus quam nisi at ante. Pellentesque vitae lobortis enim. Fusce efficitur turpis eu odio consequat, eu sagittis arcu varius. Integer purus lacus, semper in libero ac, pretium fermentum massa. Aenean sed lorem tempor, volutpat nunc nec, faucibus nisl.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      -
      -
      -
      -
      -
      -

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
